import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Movie SIMP",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                style={{ backgroundColor: "darkgrey" }}
                className={inter.className + " all-font"}
            >
                <Header></Header>
                <main>{children}</main>
            </body>
        </html>
    );
}
